name: Build and deploy on Itch.io 

on:
  workflow_dispatch:

jobs:
  sendTagAnnotations:
    name: Send information to Telegram
    runs-on: ubuntu-latest
    steps:
      # Normal message
      - uses: appleboy/telegram-action@master
        env:
          version: $(git describe --tags --abbrev=0 --match v[0-9]*)
        with:
          to: ${{ secrets.TELEGRAM_TO_TSM }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: RELEASE builds of ${{ secrets.UNITY_PROJECT_NAME }} in process. Last version ${{ env.version }}
          
          
  buildForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} with itchio channel ${{ matrix.itch_channel }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - targetPlatform: StandaloneWindows64   # Build a Windows 64-bit standal
            itch_channel: windows
          - targetPlatform: StandaloneLinux64 # Build a Windows 64-bit standal
            itch_channel: linux
          - targetPlatform: StandaloneOSX # Build a macOS standalone (Intel 64-bit).
            itch_channel: mac
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Checkout last tag
        id: lasttag
        run: |
          lasttag=$(git describe --tags --abbrev=0 --match v[0-9]*)
          version=${lasttag:1}
          echo "::set-output name=lasttag::$lasttag"
          echo "::set-output name=version::$version"
          git checkout $lasttag
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        id: BuildStep
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          buildName: ${{ secrets.UNITY_PROJECT_NAME}}
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
      - name: Rename game folder
        id: renaming
        run: |
          mkdir renamed
          cp -r build/${{ matrix.targetPlatform }} renamed
          mv renamed/${{ matrix.targetPlatform }} renamed/${{ secrets.UNITY_PROJECT_NAME }}
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.SOLAR_BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.itch_channel }}
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: renamed
          VERSION: ${{ steps.lasttag.outputs.version }}
  
  sendFinalInformation:
    name: Send final information to Telegram
    needs: buildForSomePlatforms
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_TSM }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: All builds completed succesfully.